# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - svelte-rich-text

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["svelte-rich-text"]  # This triggers the deployment after svelte-rich-text workflow completes
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'svelte-rich-text'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        images: 'index.docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/svelte-rich-text:commit-${{ github.sha }}'
